### ISSUE TITLE
Behaviour - 'Land Helicopter' has no way to take off again

### ISSUE THREAD

**Issue by astruyk** [astruyk/Ares#120]
Once a helicopter finally decides to land, he never takes off again.

Ideally there would be a way to get them to stay landed until you issue new orders. Not sure how that would work. I'm not happy about having to have a 'take off' module to undo the landing behaviour.

**Comment by Wolfenswan** [comment]
For my function [here](https://github.com/Wolfenswan/ws_fnc/blob/master/AI/fn_taskLand.sqf) I've kinda forced this behavior (see line 104 to 124).

**Comment by astruyk** [comment]
Thanks. I was also going to try the 'make a temporary invisible landing pad' thing to get the stupid helo to land where I wanted. I just haven't had time to revisit this functionality at all. Good to have a some code to look at that might actually work :)

**Comment by TheOtherTaylor** [comment]
As a curiosity, at line 76 you have
...
 _pilot setBehaviour "CARELESS";
...
Does this actually have an effect on the flight path versus other behaviours?  I would assume the important part is to disallow fleeing which you did in the next line.

Additionally, when the unit sees contact, will it not switch it's behaviour immediately to Combat?

**Comment by astruyk** [comment]
In both "CARELESS" and "SAFE" units will follow different paths (e.g. for
vehicles they will stick to the roads more, and not avoid trees and ambush
points and stuff). "CARELESS" is different from "SAFE" in that it shouldn't
automatically change to combat if enemies are encountered. See
https://community.bistudio.com/wiki/Mission_Editor:_Waypoints#Behaviour

**Comment by Wolfenswan** [comment]
As the comments say, these lines are open for experimentation. I've seen the pilots land fine when commenting this specific line (thus them being set to "AWARE"), even with combat around them.

**Comment by TheOtherTaylor** [comment]
Anton, I meant particularly for helicopters.  I am aware that infantry and ground vehicle behaviours and pathing change.

If i get some time tomorrow I'll be able to get on and watch helicopters land for a while to see if they do anything different.

The only thing I know besides findEmptyPosition is the invisible (or visible) helipads.  They seem to prioritize those above all else, even when it's in a bad location.

**Comment by astruyk** [comment]
Closed. See comment on #119.
