### ISSUE TITLE
Save/Load - Save units as well as static objects

### ISSUE THREAD

**Issue by astruyk** [astruyk/Ares#147]
Right now we don't save unit positions because there's a lot more data needed for them. It's a pretty commonly requested feature.

In order for this to be complete we should at least save:
* Unit types and groups
* Unit Positions and orientations
* Waypoints and waypoint types

It's going to break the existing save/load format because there's no space for that info. Could probably be made to at least be backwards compatible (by storing unit info in a later section and early-outing based on version numbering).

**Comment by alexcroox** [comment]
This would be great. Currently I'm using MCC + Zeus to fill out the mission base and MCC's save to mission sqm. Would be great to ditch that requirement.

**Comment by astruyk** [comment]
I'm considering this fixed as of 1.7.0. In 1.8.0 the old saving system will be fully deprecated.
