### ISSUE TITLE
Save/Load - Add 'Whole Map' option when saving objects to clipboard

### ISSUE THREAD

**Issue by astruyk** [astruyk/Ares#148]
Title pretty much sums it up.

I think there might be some weird issues where 'Logic' entities are being grabbed when they shouldn't (which is why this wansn't implemented originally). That should be verified and fixed if necessary if that's the case.

**Comment by alexcroox** [comment]
Would be useful if a user could drag an area/currently selected object/units to save out too. Sometimes I'll start a mission in the editor then finish placing things in zeus and I don't want to save the objects placed in the editor.

**Comment by astruyk** [comment]
Old saving system is deprecated. New saving system has this feature.
