### ISSUE TITLE
Request: A module that adds Virtual Arsenal to an object placed in Zeus

### ISSUE THREAD

**Issue by krieger26** [astruyk/Ares#169]
When using many weapon mods, standard ammo boxes don't cut it. It would make quick resupply for units in the field much faster if you could spawn in an object then add VA to it so the players can arm themselves easily.

**Comment by GloryAndPain** [comment]
Try this code for the ammo boxes while in mission:

    [["%ALL"],
    ["%ALL"],
    ["%ALL"],
    ["%ALL"],
    [[],[]],
    [[],[]],
    [[],[]],
    [[],[]]]


Use this one for pre-placed boxed in mission:

    this allowDamage false; ["AmmoboxInit",[this,true]] call BIS_fnc_arsenal;

**Comment by astruyk** [comment]
Fixed in 2175b2975733be083f754dda20e7aae1728f6521
