### ISSUE TITLE
Equipment - Remove all attachments (optics) module

### ISSUE THREAD

**Issue by astruyk** [astruyk/Ares#171]
From forum ( http://forums.bistudio.com/showthread.php?185254-Ares-Modules-expanding-Zeus-functionality-Release-Thread&p=2848410&viewfull=1#post2848410 )

> What about the ability to remove all optics by faction similar to the remove NVGs/Thermals option?

**Comment by Wolfenswan** [comment]
A similar option to remove/add silencers would be neat as well.

**Comment by TheOtherTaylor** [comment]
I feel like this could be a slowly growing add/remove equipment list.  Is it worth considering a more blanket system for modifying unit equipment?  I really don't know how this might work off the top of my head, but I have this feeling people will keep requesting little additions and the code could get cumbersome.

**Comment by Wolfenswan** [comment]
I think with a general option for optics, one for NVG/flashlights and one for silencers you've got all the options you need for the vanilla game.

**Comment by astruyk** [comment]
I'll probably just add these few more options - the 'Equipment' tab isn't really overflowing with complicated stuff at the moment.
