### ISSUE TITLE
Default AI skill level

### ISSUE THREAD

**Issue by alexcroox** [astruyk/Ares#175]
Is there a way to set the AI skill level by default for zeus placed units? I have to manually go and set skill to low to tone down the aimbotting mode they tend to have by default and it takes a fair amount of my time.

**Comment by astruyk** [comment]
There is not a function for this. I'm not planning on adding one since there are already good AI mods that cover that better than I could. Take a look at ASR_AI3 or bCombat - we've had success with both of those on our server using Zeus in both private and public missions.
