### ISSUE TITLE
Add some example AGM/ACE custom modules that can be used if that mod is enabled

### ISSUE THREAD

**Issue by astruyk** [astruyk/Ares#182]
Once #176 is fixed we'll be able to add new modules on the fly (e.g. if we detect the presence of certain mods we can add new entries into the Zeus slot). When that is done, it'd be nice to implement some of the following via. AGM:
- [ ] Handcuff/Release Handcuffs
- [ ] Wound/Heal units
- [ ] Make/Unmake Medic
- [ ] Make/Unmake Explosives Expert
- [ ] Make/Unmake Pilot
- [ ] Add Spare Wheel
- [ ] Add Spare Jerry Can

**Comment by jonpas** [comment]
I'd add:
- Repair (whole or choice of part) 
- Refuel (full or choice of litres)

**Comment by astruyk** [comment]
On hold until ACE comes out. The will reevaluate.

**Comment by TheOtherTaylor** [comment]
Ace seems to be adding their own Zeus functionality for their modules (surrender, handcuff, make unconscous).  We can probably close this.

**Comment by jonpas** [comment]
https://github.com/acemod/ACE3/issues/130

**Comment by astruyk** [comment]
Agreed. Closing.
