### ISSUE TITLE
Attach to

### ISSUE THREAD

**Issue by dav-is** [astruyk/Ares#183]
I think my missions could benefit if I could attach static weapons to things and objects to vehicles. 

How I think it could work:
2 modules, the first module would select the 1st object, the other module would attach it with a popup asking for x,y,z

**Comment by MoistBaguette** [comment]
Did almost the exact thing for my Fork.

Take a look at this for the Attach Module:
https://bitbucket.org/terriblecoders/arma3-ares/src/71e8c650669ced865e748bcac8942a75f356c35d/src/ares_zeusExtensions/modules/Util/fn_AttachToObject.sqf?at=master

And here for the Release Module:
https://bitbucket.org/terriblecoders/arma3-ares/src/71e8c650669ced865e748bcac8942a75f356c35d/src/ares_zeusExtensions/modules/Util/fn_DetachObject.sqf?at=master

May be a bit rudimentary and some things are a bit bothersome, mainly setDir not always rotating an object correctly to the direction it faced after attaching it to the object.
