### ISSUE TITLE
Remove current 'Save/Load' modules (deprecated as of 1.7.0)

### ISSUE THREAD

**Issue by astruyk** [astruyk/Ares#188]
As of 1.7.0 I'm no longer officially supporting the 'Copy to clipboard', 'Paste into old position' and 'Paste into new position' modules. These need to be removed in 1.8.0.

**Comment by alexcroox** [comment]
Do you plan to provide the ability to save as a mission? i.e don't just generate SQF but an actual SQM with everything that is on the map.

**Comment by jonpas** [comment]
make_file.dll from KillzoneKid might be useful for SQM export. X-Cam uses it for both SQM and terrain builder exports I believe.

**Comment by alexcroox** [comment]
What does MCC use as that's currently how I make my missions files when I build them in zeus.

**Comment by astruyk** [comment]
I don't have any plans to export in SQM format. It's pretty trivial to implement a mission by placing the generated SQF into an file in your mission folder and have that populate the mission on startup. In the simplest case you can just make an init.sqf and paste the whole chunk in an `if(isServer) then { ... };` block.

Also writing SQM means more than double the work, since SQM is both another possible output type, and a terrible, complex format. The only advantage I see of being able to write out that format is that you could manipulate things in the editor - which would be nice, but isn't worth the effort IMO.

If someone wants to submit a module for the 'Extras' folder that does it that'd be awesome, but I'm not going to do it as part of core Ares because I'm not going to be responsible for maintaining it.

Lastly, with BIS's talk of implementing a real 3D editor, IMO this is all throwaway work and will probably be cut whenever that feature comes online.

**Comment by astruyk** [comment]
Regarding the make_file.dll - I spent a while thinking about it, but I decided not to attempt to dump out an actual file on disk. Writing files to the user's machine (or potentially the server if it is running Ares) is a very very scary proposition for a mod that is being used in multiplayer. I'm not going down that road.

The existing copy-paste functionality is clunky, but it works and is safe. Anything you paste into those boxes was at least pasted by you. And even if it is compromised, at least you can just restart the mission without worrying that it did something to your client/server machine.

**Comment by jonpas** [comment]
I agree totally, make_file.dll is not even supposed to be used in multiplayer, anyways, I was just throwing it out there. And TBH we have X-Cam now for that, and with official 3D editor, as you said, it's not worth it.

**Comment by alexcroox** [comment]
Agreed on all points, Ares was never pitched as a mission editor/maker, just thought I'd try my luck :tongue: 

Looking forward to their 3D editor.

**Comment by astruyk** [comment]
Also, if there are any arguments for keeping the old save/load functionality around this would be a good time to bring them up :)

Right now the one thing (that I know of) that can be done with that system that can't be done with the generated SQF code is that you can't paste things into new positions. You can paste them and then move them, but since that info is baked into the SQF code when it's generated you can't just drop them like a composition. I'd considered trying to make it work, but the generated code required was way more complicated and broke one of the awesome advantages of having actual SQF code: you don't actually need Ares to run it - you can drop it into any old mission and it'll work.

**Comment by xgp0006** [comment]
So i guess i tried to do the following: if(isServer) then { ... }; and pasted my composition into the brackets but nothing is popping up.What is your number one recommended way to execute the new SQF generated code?

<script src="http://pastebin.com/embed_js.php?i=kw2ttxSx"></script>

**Comment by astruyk** [comment]
The way I do it when I'm running a mission (to load a saved mission) is to simply drop the `Util -> Execute Code (Local)` module into the world and paste the generated SQF in there. It should remake the objects that were saved. You can use the `Util -> Add Objects To Zeus` module to make the new objects editable again.

If you have a mission and you want it to load all the time automatically, you can paste it into your init.sqf like the following:
```
if (isServer) then
{
    /// Paste code here.
};
```
The if(...) prevents it from being re-run everytime a new player joins, and only the server will run it.

I recommend that, as Zeus, you always run with the 'show script errors' argument enabled for the game - that way if something fails you get an actual error message and not a silent failure. You can also check your RPT log ( https://community.bistudio.com/wiki/Crash_Files ) to see what went wrong if you miss the message (or if that setting is disabled).

**Comment by xgp0006** [comment]
I have put that code in the init.sqf with the generated code but perhaps since im in preview mode in editor its not executing this? cause its not working this way for me at this time. HOWEVER the module with zeus/Ares worked instantly smoother than load/save and  beautifully like a charm! Is there a way to enablesimulation false on static objects to assist in framerate drops on compositions but in a radius to help save frames from small objects?

**Comment by astruyk** [comment]
No, but you could write a custom module for it if you wanted to.

**Comment by xgp0006** [comment]
If i was only so talented but this is wise. ill see whom i can dig up as it would be a good module...Thank you for your support!

**Comment by IceMunney** [comment]
I find the cut and paste option good for creating quick missions I have standard set up for different bases and other areas that I can added together or use separately to either use for attacking or defending that I can quickly set up by pasting then and then manning them  with the required troops.

Not having that ability will have making missions slow to set up as you will be starting from scratch

**Comment by astruyk** [comment]
In 1.8.0
