### ISSUE TITLE
Generate Mission SQF - Execute Code for AAF - Civil Units

### ISSUE THREAD

**Issue by Talyataya** [astruyk/Ares#192]
When generating a mission SQF , I see its copying everything but when I paste on Execute Code module, it will not paste any AAF or Civil units on foot(Pasting AAF - Civil units in vehicles is working properly)

**Comment by astruyk** [comment]
Can you paste the Sq that is generated here or somewhere like paste in (if
it's too long)? might just be something with the generated code....

**Comment by Talyataya** [comment]
I tried multiple times and every single time it happens so basically anything that has AAF or civilian on foot does the same thing but sure here one is:



 _newGroup = createGroup GUER; _newUnit = _newGroup createUnit ['I_Soldier_TL_F', [9216.18,21614.1,0.00143242], [], 0, 'CAN_COLLIDE']; _newUnit setSkill 0.5; _newUnit setRank 'SERGEANT'; _newUnit setFormDir 0; _newUnit setDir 0; _newUnit setPosASL [9216.18,21614.1,15.6176];_newUnit = _newGroup createUnit ['I_Soldier_AR_F', [9221.18,21609.1,0.00155258], [], 0, 'CAN_COLLIDE']; _newUnit setSkill 0.5; _newUnit setRank 'CORPORAL'; _newUnit setFormDir 15; _newUnit setDir 15; _newUnit setPosASL [9221.18,21609.1,15.8675];_newUnit = _newGroup createUnit ['I_Soldier_GL_F', [9211.18,21609.1,0.00146008], [], 0, 'CAN_COLLIDE']; _newUnit setSkill 0.5; _newUnit setRank 'PRIVATE'; _newUnit setFormDir 345; _newUnit setDir 345; _newUnit setPosASL [9211.18,21609.1,15.6779];_newUnit = _newGroup createUnit ['I_Soldier_LAT_F', [9226.18,21604.1,0.00135231], [], 0, 'CAN_COLLIDE']; _newUnit setSkill 0.5; _newUnit setRank 'PRIVATE'; _newUnit setFormDir 57.6; _newUnit setDir 57.6; _newUnit setPosASL [9226.18,21604.1,16.1145];_newGroup setFormation 'WEDGE'; _newGroup setCombatMode 'YELLOW'; _newGroup setBehaviour 'AWARE'; _newGroup setSpeedMode 'NORMAL';_newGroup = createGroup GUER; _newUnit = _newGroup createUnit ['I_Soldier_SL_F', [9252.35,21566.2,0.00141716], [], 0, 'CAN_COLLIDE']; _newUnit setSkill 0.5; _newUnit setRank 'SERGEANT'; _newUnit setFormDir 30; _newUnit setDir 30; _newUnit setPosASL [9252.35,21566.2,16.9773];_newUnit = _newGroup createUnit ['I_Soldier_AA_F', [9227.06,21567.2,0.0014286], [], 0, 'CAN_COLLIDE']; _newUnit setSkill 0.5; _newUnit setRank 'CORPORAL'; _newUnit setFormDir 330; _newUnit setDir 330; _newUnit setPosASL [9227.06,21567.2,16.7642];_newUnit = _newGroup createUnit ['I_Soldier_AA_F', [9260.79,21560.4,0.00143623], [], 0, 'CAN_COLLIDE']; _newUnit setSkill 0.5; _newUnit setRank 'PRIVATE'; _newUnit setFormDir 103.225; _newUnit setDir 103.225; _newUnit setPosASL [9260.79,21560.4,17.0019];_newUnit = _newGroup createUnit ['I_Soldier_AA_F', [9219.38,21561.8,0.00144577], [], 0, 'CAN_COLLIDE']; _newUnit setSkill 0.5; _newUnit setRank 'PRIVATE'; _newUnit setFormDir 261.496; _newUnit setDir 261.496; _newUnit setPosASL [9219.38,21561.8,16.719];_newUnit = _newGroup createUnit ['I_Soldier_AAT_F', [9266.67,21554.7,0.00144386], [], 0, 'CAN_COLLIDE']; _newUnit setSkill 0.5; _newUnit setRank 'PRIVATE'; _newUnit setFormDir 104.712; _newUnit setDir 104.712; _newUnit setPosASL [9266.67,21554.7,17.0108];_newUnit = _newGroup createUnit ['I_Soldier_AAA_F', [9215.6,21554.8,0.00144005], [], 0, 'CAN_COLLIDE']; _newUnit setSkill 0.5; _newUnit setRank 'PRIVATE'; _newUnit setFormDir 255.409; _newUnit setDir 255.409; _newUnit setPosASL [9215.6,21554.8,16.6734];_newUnit = _newGroup createUnit ['I_Soldier_AAA_F', [9272.91,21551,0.00145149], [], 0, 'CAN_COLLIDE']; _newUnit setSkill 0.5; _newUnit setRank 'PRIVATE'; _newUnit setFormDir 100.394; _newUnit setDir 100.394; _newUnit setPosASL [9272.91,21551,16.9774];_newUnit = createVehicle ['I_APC_tracked_03_cannon_F', [9239.21,21584.6,-0.310455], [], 0, 'CAN_COLLIDE']; createVehicleCrew _newUnit; (crew _newUnit) join _newGroup; _newUnit setDir 359.983; _newUnit setFormDir 359.983; _newUnit setPosASL [9239.21,21584.6,16.472];_newGroup setFormation 'WEDGE'; _newGroup setCombatMode 'YELLOW'; _newGroup setBehaviour 'AWARE'; _newGroup setSpeedMode 'NORMAL';_newGroup = createGroup GUER; _newUnit = _newGroup createUnit ['I_Soldier_AR_F', [9186.07,21580.9,0.00136375], [], 0, 'CAN_COLLIDE']; _newUnit setSkill 0.5; _newUnit setRank 'PRIVATE'; _newUnit setFormDir 0; _newUnit setDir 0; _newUnit setPosASL [9186.07,21580.9,16.2164];_newGroup setFormation 'WEDGE'; _newGroup setCombatMode 'YELLOW'; _newGroup setBehaviour 'AWARE'; _newGroup setSpeedMode 'NORMAL';_newGroup = createGroup GUER; _newUnit = createVehicle ['I_APC_tracked_03_cannon_F', [9218.91,21588.3,-0.302782], [], 0, 'CAN_COLLIDE']; createVehicleCrew _newUnit; (crew _newUnit) join _newGroup; _newUnit setDir 0.0112827; _newUnit setFormDir 0.0112827; _newUnit setPosASL [9218.91,21588.3,16.2367];_newGroup setFormation 'WEDGE'; _newGroup setCombatMode 'YELLOW'; _newGroup setBehaviour 'AWARE'; _newGroup setSpeedMode 'NORMAL';

**Comment by Talyataya** [comment]
When I change = createGroup GUER; to = createGroup RESISTANCE looks like it is working fine.

**Comment by astruyk** [comment]
I'll look into this for the next version. Should be easy to fix in the script now that I know what it is. Thanks for following up and pasting the solution.

**Comment by Talyataya** [comment]
And thanks to you for creating such a great and useful mod.

**Comment by astruyk** [comment]
Fixed in 48926cc1959e2fe0d04794162e901f5397ee87f3
