### ISSUE TITLE
Add enable/disable simuation module

### ISSUE THREAD

**Issue by astruyk** [astruyk/Ares#201]
It would be nice to be able to turn off physics for some objects during missions to prevent them from flipping out with physics.

**Comment by TheOtherTaylor** [comment]
Ooh, I've been wanting to do this.  It should be pretty straight-forward using this (community.bistudio.com/wiki/enableSimulation)

**Comment by jonpas** [comment]
Rather https://community.bistudio.com/wiki/enableSimulationGlobal
