### ISSUE TITLE
Ares 1.8.2 Does not work on Linux server.

### ISSUE THREAD

**Issue by Marcin648** [astruyk/Ares#229]
Hello!
I test Ares only with @CBA_A3 on Linux Dedicate Server.
Server exits with error during startup.

Logs:

`10:49:29 ../lib/Network/networkServer.cpp ClearNetServer:NOT IMPLEMENTED - briefing!`
`Cannot open file '/home/arma3/serverfiles/@Ares\addons\ares_zeusextensions`
`10:49:29 Critical:Destroying running thread!`
`10:49:29 Critical:Destroying running thread!`
`10:49:29 Critical:Destroying running thread!`

**Comment by larsrusteberg** [comment]
Hello,
did you try lowercasing all files? This usually does the trick for me.

**Comment by Marcin648** [comment]
@larsrusteberg Yes! Work now. Works when I rename ares_zeusExtensions.pbo to ares_zeusextensions.pbo.
Thx
